### ISSUE TITLE
JDBC source connector error

### ISSUE THREAD

**Issue by JanardhanVarikuti** [Landoop/kafka-connect-ui#63] opened 2018-02-08 05:16 UTC
I'm trying to get the data from Oracle db into the kafka topics by using the  JDBC Source connector.

 1>  I've selected the JDBC source connector from the available connectors through connect UI (Landoop)
     Here are my properties :
            name=JDBC-source-connector-demo
    connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.password= oracle12
connection.url= jdbc:oracle:thin:@1.1.1.1:33333/ABCDE
connection.user= ORACLE_LA_USR
table.types=VIEW
query=select * from STUDENTS123
mode=timestamp
timestamp.column.name=SYSTEM_N
topic.prefix=JDBC_DB_TOPIC_DEMO
batch.max.rows= 100

transforms=createKey,extract
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=ROLL_N
transforms.extract.type=org.apache.kafka.connect.transforms.ExtractField$Key
transforms.extract.field=ROLL_N

2> After pasting the above properties, I see the following errors in the connect UI

      

Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@1.1.1.1:33333/ABCDE for configuration Couldn't open connection to jdbc:oracle:thin:@1.1.1.1:33333/ABCDE
Invalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@1.1.1.1:33333/ABCDE for configuration Couldn't open connection to jdbc:oracle:thin:@1.1.1.1:33333/ABCDE

3> Should I need to paste the ojdbc.jar in some path? If yes, could you please let me know the same ?
    I believe ojdbc.jar is already packaged with confluent (which is again packaged as part of the Landoop I believe )

My Landoop kafka connect UI version - 

Kafka Connect : /api/kafka-connect 
Kafka Connect Version : 0.11.0.1-cp1 
Kafka Connect UI Version : 0.9.4 

4> And I'm not able to see the connectors in the connect UI even after starting the kafka cluster.

**Comment by Antwnis** [comment] 2018-02-08 11:50
Hi @JanardhanVarikuti I believe that `No suitable driver found` means that you have not included the Oracle JDBC driver in the classpath of Kafka Connect

The JDBC connector is generic and requires the DB specific driver to be added in the classpath

**Comment by JanardhanVarikuti** [comment] 2018-02-08 12:58
Hi @Antwnis 
Thank for the prompt response.

I've set the classpath as follows -

export CLASSPATH=/home/janardhan/Documents/Kafka/code-0/code/source/JDBC_Source/JDBC_jar/ojdbc7.jar:$CLASSPATH

But still getting the same error.

Let me know if I'm setting it correctly.

**Comment by Antwnis** [comment] 2018-02-08 19:47
Closing as it was resolved

**Closed by Antwnis** 2018-02-08 19:47 UTC

**Comment by JanardhanVarikuti** [comment] 2018-02-08 20:02
After pasting the ojdbc7.jar in the following path, the issue is resolved.
/opt/confluent/share/java/kafka-connect-jdbc

**Comment by smaue** [comment] 2018-07-02 11:11
Hi Guys,
I am facing same issue 

{"error_code":400,"message":"Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@ldap://oid.allstate.com:389/cn=OracleContext,dc=allstate,dc=com/<DBname>

i have copied ojdbc8.jar in /apps/confluent/share/java/kafka-connect-jdbc folder

**Comment by Antwnis** [comment] 2018-07-02 14:21
Have u copied the JAR in all Kafka Connect workers ?
Have you restarted all your Connect workers for the classpath to be re-loaded ? @smaue

**Comment by minormadrigal** [comment] 2019-06-04 19:51
Hi I am experiencing the same issue, I have loaded the driver in all the workers, the driver seems to be properly loaded

DEBUG Loading plugin urls: [file:/usr/share/java/kafka-connect-jdbc/audience-annotations-0.5.0.jar, file:/usr/share/java/kafka-connect-jdbc/common-utils-5.0.1.jar, file:/usr/share/java/kafka-connect-jdbc/jline-0.9.94.jar, file:/usr/share/java/kafka-connect-jdbc/jtds-1.3.1.jar, file:/usr/share/java/kafka-connect-jdbc/kafka-connect-jdbc-5.0.1.jar, file:/usr/share/java/kafka-connect-jdbc/netty-3.10.6.Final.jar, file:/usr/share/java/kafka-connect-jdbc/ojdbc7.jar, file:/usr/share/java/kafka-connect-jdbc/postgresql-9.4-1206-jdbc41.jar, file:/usr/share/java/kafka-connect-jdbc/slf4j-api-1.7.25.jar, file:/usr/share/java/kafka-connect-jdbc/sqlite-jdbc-3.25.2.jar, file:/usr/share/java/kafka-connect-jdbc/zkclient-0.10.jar, file:/usr/share/java/kafka-connect-jdbc/zookeeper-3.4.13.jar] 

This is my connection url:

"connection.url":"jdbc:oracle:thin:@remote-host:1621:testDB"

I have the same connector deployed in a different environment (dev environment) and everything works as expected, the issue is happening only on Staging.

This is the error that I am getting

Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@remote-host:1621:testDB for configuration Couldn't open connection to jdbc:oracle:thin:@remote-host:1621:testDB\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@remote-host:1621:testDB for configuration Couldn't open connection to jdbc:oracle:thin:@remote-host:1621:testDB\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"}

**Comment by stheppi** [comment] 2019-06-04 19:53
@minormadrigal 
`java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@remote-host:1621:testDB` 

this tells you the driver is not available.

**Comment by minormadrigal** [comment] 2019-06-04 19:55
yes, but you as you can see the driver was supposed  loaded properly

DEBUG Loading plugin urls: [file:/usr/share/java/kafka-connect-jdbc/audience-annotations-0.5.0.jar, file:/usr/share/java/kafka-connect-jdbc/common-utils-5.0.1.jar, file:/usr/share/java/kafka-connect-jdbc/jline-0.9.94.jar, file:/usr/share/java/kafka-connect-jdbc/jtds-1.3.1.jar, file:/usr/share/java/kafka-connect-jdbc/kafka-connect-jdbc-5.0.1.jar, file:/usr/share/java/kafka-connect-jdbc/netty-3.10.6.Final.jar, **file:/usr/share/java/kafka-connect-jdbc/ojdbc7.jar**, file:/usr/share/java/kafka-connect-jdbc/postgresql-9.4-1206-jdbc41.jar, file:/usr/share/java/kafka-connect-jdbc/slf4j-api-1.7.25.jar, file:/usr/share/java/kafka-connect-jdbc/sqlite-jdbc-3.25.2.jar, file:/usr/share/java/kafka-connect-jdbc/zkclient-0.10.jar, file:/usr/share/java/kafka-connect-jdbc/zookeeper-3.4.13.jar]

**Comment by stheppi** [comment] 2019-06-04 20:04
When you run connect you should see 

```INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector'```
immediately after this, and before any other plugins being logged, you should see your JDBC driver being registered:
```
INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
DEBUG Registered java.sql.Driver: com.mysql.cj.jdbc.Driver@7bbbb6a8 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
DEBUG Registered java.sql.Driver: org.postgresql.Driver@ea9e141 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
DEBUG Registered java.sql.Driver: org.sqlite.JDBC@236134a1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```
Ensure that your JDBC driver is included in the list of those registered. If it’s not, then you’ve not installed it correctly.

Note that you might see Registered java.sql.Driver for your driver elsewhere in the log, but for validation that it will be available to the JDBC connector, it must appear directly after the 
```INFO Added plugin 'io.confluent.connect.jdbc message.```

**Comment by minormadrigal** [comment] 2019-06-04 20:06
thanks for the quick response @stheppi, the plugin is properly loaded

```
[2019-06-04 19:22:38,966] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-06-04 19:22:38,966] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-06-04 19:22:38,969] DEBUG Registered java.sql.Driver: jTDS 1.3.1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
**[2019-06-04 19:22:38,995] DEBUG Registered java.sql.Driver: oracle.jdbc.OracleDriver@773dab28 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)**
[2019-06-04 19:22:38,999] DEBUG Registered java.sql.Driver: org.postgresql.Driver@7aad3f7d to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2019-06-04 19:22:39,001] DEBUG Registered java.sql.Driver: org.sqlite.JDBC@4abf3f0 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

**Comment by antpersan** [comment] 2019-08-30 10:54
> thanks for the quick response @stheppi, the plugin is properly loaded
> 
> ```
> [2019-06-04 19:22:38,966] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
> [2019-06-04 19:22:38,966] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
> [2019-06-04 19:22:38,969] DEBUG Registered java.sql.Driver: jTDS 1.3.1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
> [2019-06-04 19:22:38,995] DEBUG Registered java.sql.Driver: oracle.jdbc.OracleDriver@773dab28 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
> [2019-06-04 19:22:38,999] DEBUG Registered java.sql.Driver: org.postgresql.Driver@7aad3f7d to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
> [2019-06-04 19:22:39,001] DEBUG Registered java.sql.Driver: org.sqlite.JDBC@4abf3f0 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
> ```

@minormadrigal, Did you resolve the issue? I have exactly the same issue
